# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
