# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_travels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travels',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travels',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travels',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
